name: e2e
description: Secure communication system

publish_to:
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  socket_io_client: 2.0.0-beta.4-nullsafety.0
  openpgp: 2.0.1
  flutter_chat_bubble: 2.0.0
  expandable: ^5.0.1
  flutter_webrtc: ^0.8.10
  sdp_transform: ^0.3.2
  flutter_ringtone_player: ^3.2.0
  wakelock: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - packages/openpgp/web/assets/worker.js
    - packages/openpgp/web/assets/wasm_exec.js
    - packages/openpgp/web/assets/openpgp.wasm
  fonts:
    - family: Rubik
      fonts:
        - asset: fonts/Rubik-VariableFont_wght.ttf
    - family: AnekBangla
      fonts:
        - asset: fonts/Rubik-VariableFont_wght.ttf


  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
